import {first} from '../../har/parameters.js';
const specs=[
['GA4',/google-analytics\.com\/g\/collect|google-analytics\.com\/collect.*[?&]v=2/,p=>({tag_id:first(p,'tid'),event_name:first(p,'en')})],
['GTM',/googletagmanager\.com\/(?:gtm|gtag)\.js/,p=>({tag_id:first(p,'id')})],
['Google Ads',/googleadservices\.com\/pagead\/conversion|google\.com\/pagead\/1p-conversion/,p=>({tag_id:first(p,'conversion_id','id'),conversion_label:first(p,'label')})],
['CM360/Floodlight',/fls\.doubleclick\.net\/activityi|ad\.doubleclick\.net\/activity/,p=>({tag_id:first(p,'src'),event_name:first(p,'type'),conversion_label:first(p,'cat'),floodlight:{advertiser_source_id:first(p,'src'),activity_group:first(p,'type'),activity_tag:first(p,'cat'),counting_type:first(p,'qty'),ord:first(p,'ord'),num:first(p,'num'),custom_variables:Object.fromEntries(Object.entries(p).filter(([k])=>/^u\d+$/.test(k)))}})],
['Meta',/facebook\.com\/tr\/?/,p=>({tag_id:first(p,'id'),event_name:first(p,'ev')})],['TikTok',/analytics\.tiktok\.com|tiktok\.com\/i18n\/pixel/,p=>({tag_id:first(p,'pixel_code','id'),event_name:first(p,'event')})],['Pinterest',/ct\.pinterest\.com\/v3|pinterest\.com\/v3/,p=>({tag_id:first(p,'tid','tag_id'),event_name:first(p,'event')})],['LinkedIn',/linkedin\.com\/(?:collect|px)|snap\.licdn\.com/,p=>({tag_id:first(p,'pid'),event_name:first(p,'conversionId')})],['Microsoft UET',/bat\.bing\.com\/action|bat\.bing\.com\/p\/action/,p=>({tag_id:first(p,'ti'),event_name:first(p,'ea','evt')})],['Microsoft Clarity',/clarity\.ms\/(?:collect|tag)/,p=>({tag_id:first(p,'id')})],['Adobe Analytics',/(?:omtrdc\.net|2o7\.net)\/b\/ss\//,p=>({tag_id:(p._path||[])[0]||null,event_name:first(p,'events','pev2')})],['Hotjar',/hotjar\.com|hotjar\.io/,p=>({tag_id:first(p,'site_id','id'),event_name:first(p,'event')})]
];
export function exactParser(url,p){for(const [vendor,re,enrich] of specs)if(re.test(url)){const e=enrich(p);return {vendor,category:vendor==='GTM'?'tag-management':vendor==='Hotjar'||vendor==='Microsoft Clarity'?'replay':'analytics',classification_method:'recognised',classification_confidence:'high',...e}}return null}
